apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::013345477993:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::013345477993:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1E4U3JG0G1GY6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-05T03:14:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1200"
  uid: 831d2d91-930c-4a06-b9cb-afec480831e7
